# Copyright Red Hat

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-registration-webhook-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-registration-webhook-service
subjects:
  - kind: ServiceAccount
    name: cluster-registration-webhook-service
    namespace: {{ .Namespace }}
 